-----------------------------------------------------------------------------
-- ASSIGNMENT_ASSIGNMENT
-----------------------------------------------------------------------------

CREATE TABLE ASSIGNMENT_ASSIGNMENT
(
    ASSIGNMENT_ID VARCHAR (99) NOT NULL,
	CONTEXT VARCHAR (99),
    XML LONGTEXT
);

CREATE UNIQUE INDEX ASSIGNMENT_ASSIGNMENT_INDEX ON ASSIGNMENT_ASSIGNMENT
(
	ASSIGNMENT_ID
);

CREATE INDEX ASSIGNMENT_ASSIGNMENT_CONTEXT ON ASSIGNMENT_ASSIGNMENT
(
	CONTEXT
);

-----------------------------------------------------------------------------
-- ASSIGNMENT_CONTENT
-----------------------------------------------------------------------------

CREATE TABLE ASSIGNMENT_CONTENT
(
    CONTENT_ID VARCHAR (99) NOT NULL,
	CONTEXT VARCHAR (99),
    XML LONGTEXT
);

CREATE UNIQUE INDEX ASSIGNMENT_CONTENT_INDEX ON ASSIGNMENT_CONTENT
(
	CONTENT_ID
);

CREATE INDEX ASSIGNMENT_CONTENT_CONTEXT ON ASSIGNMENT_CONTENT
(
	CONTEXT
);

-----------------------------------------------------------------------------
-- ASSIGNMENT_SUBMISSION
-----------------------------------------------------------------------------

CREATE TABLE ASSIGNMENT_SUBMISSION
(
    SUBMISSION_ID VARCHAR (99) NOT NULL,
	CONTEXT VARCHAR (99),
    XML LONGTEXT
);

CREATE UNIQUE INDEX ASSIGNMENT_SUBMISSION_INDEX ON ASSIGNMENT_SUBMISSION
(
	SUBMISSION_ID
);

CREATE INDEX ASSIGNMENT_SUBMISSION_CONTEXT ON ASSIGNMENT_SUBMISSION
(
	CONTEXT
);

------------------------------------------------------------------------

-- ASSIGNMENT_SUBMISSION_DETAIL
------------------------------------------------------------------------

CREATE TABLE ASSIGNMENT_SUBMISSION_DETAIL
(
    SUBMISSION_ID 			VARCHAR (50) NOT NULL,
	ASSIGNMENT_ID	 		VARCHAR (99) NOT NULL,
	SITE_ID					VARCHAR (99) NOT NULL,
	DATE_RETURNED			DATETIME,
	DATE_SUBMITTED			DATETIME,
	FEEDBACK_COMMENT			LONGTEXT,
	FEEDBACK_TEXT			LONGTEXT,
	SUBMITTED				CHAR(1)
		CHECK (SUBMITTED IN ('0', '1')),
	GRADED					CHAR (1) 
		CHECK (GRADED IN ('0', '1')),
	RETURNED					CHAR (1)
		CHECK (RETURNED IN ('0', '1')),
	GRADE_RELEASED			VARCHAR (1)
		CHECK (GRADED_RELEASED IN ('0', '1')),
	HONOR_PLEDGE_FLAG		VARCHAR (0)
		CHECK (HONOR_PLEDGE_FLAG IN ('0', '1')),
	SCALED_GRADE				INTEGER,
	SUBMITTED_TEXT			LONGTEXT,
	SUBMITTER				VARCHAR(99),
	CREATED_BY				VARCHAR(99),
	MODIFIED_BY				VARCHAR(99),
	DATE_CREATED				DATETIME,
	DATE_MODIFIED			DATETIME,
	REVIEW_REPORT			VARCHAR(99),
	REVIEW_SCORE				VARCHAR(99),
	REVIEW_STATUS			VARCHAR(99)
);

ALTER TABLE ASSIGNMENT_SUBMISSION_DETAIL
		ADD (PRIMARY KEY (SUBMISSION_ID));
		
ALTER TABLE ASSIGNMENT_SUBMISSION_DETAIL
		ADD (FOREIGN KEY (ASSIGNMENT_ID) 
				REFERENCES ASSIGNMENT_ASSIGNMENT(ASSIGNMENT_ID));

ALTER TABLE ASSIGNMENT_SUBMISSION_DETAIL
		ADD (FOREIGN KEY (SITE_ID) 
				REFERENCES SAKAI_SITE(SITE_ID));

CREATE INDEX IE_ASSIGNMENT_SUBMISSION_DETAIL_SUBMITTER ON ASSIGNMENT_SUBMISSION_DETAIL
(
	SUBMITTER 	ASC
);

CREATE INDEX IE_ASSIGNMENT_SUBMISSION_DETAIL_SITEID ON ASSIGNMENT_SUBMISSION_DETAIL
(
	SITE_ID		ASC
);
------------------------------------------------------------------------

-- ASSIGNMENT_SUBMITTED_ATTACHMENT
------------------------------------------------------------------------
CREATE TABLE ASSIGNMENT_SUBMITTED_ATTACHMENT
(
    SUBMISSION_ID 			VARCHAR (50) NOT NULL,
	ATTACHMENT_ID	 		VARCHAR (255) NOT NULL
);

ALTER TABLE ASSIGNMENT_SUBMITTED_ATTACHMENT
		ADD (PRIMARY KEY (SUBMISSION_ID, ATTACHMENT_ID));

ALTER TABLE ASSIGNMENT_SUBMITTED_ATTACHMENT
		ADD (FOREIGN KEY (SUBMISSION_ID) 
				REFERENCES ASSIGNMENT_SUBMISSION_DETAIL(SUBMISSION_ID));
------------------------------------------------------------------------

-- ASSIGNMENT_FEEDBACK_ATTACHMENT
------------------------------------------------------------------------

CREATE TABLE ASSIGNMENT_FEEDBACK_ATTACHMENT
(
    SUBMISSION_ID 			VARCHAR (50) NOT NULL,
	ATTACHMENT_ID	 		VARCHAR (255) NOT NULL
);
				
ALTER TABLE ASSIGNMENT_FEEDBACK_ATTACHMENT
		ADD (PRIMARY KEY (SUBMISSION_ID, ATTACHMENT_ID));
		
ALTER TABLE ASSIGNMENT_FEEDBACK_ATTACHMENT
		ADD (FOREIGN KEY (SUBMISSION_ID) 
				REFERENCES ASSIGNMENT_SUBMISSION_DETAIL(SUBMISSION_ID));
