-----------------------------------------------------------------------------
-- ASSIGNMENT_ASSIGNMENT_T
-----------------------------------------------------------------------------

CREATE TABLE ASSIGNMENT_ASSIGNMENT_T
(
    ASSIGNMENT_ID 				VARCHAR (99) 	NOT NULL,
	CONTEXT 					VARCHAR (99)	NOT NULL,
    IS_SITE_RANGE 				CHAR(1) 		NULL
                                				   CHECK (IS_SITE_RANGE IN (0, 1)),
    OPEN_DATE					DATETIME 		NULL,
    DUE_DATE					DATETIME 		NULL,
    CLOSE_DATE					DATETIME		NULL,
    CREATED_ON					DATETIME		NULL,
    CREATED_BY					VARCHAR (99)	NULL,
    MODIFIED_ON					DATETIME		NULL,
    MODIFIED_BY					VARCHAR (99)	NULL,
    GRADE_TYPE					CHAR(1)			NULL
    												CHECK (GRADE_TYPE IN (0, 1, 2, 3, 4, 5)),
    SUBMISSION_TYPE				CHAR(1)			NULL
    												CHECK (SUBMISSION_TYPE IN (0, 1, 2, 3, 4)),
    MAX_POINT					INTEGER 		NULL,
    DRAFT						CHAR(1)			NULL
    												CHECK (DRAFT IN (0, 1)),
   	DELETED						CHAR(1)			NULL
   													CHECK (DELETED IN (0, 1)),
   	INSTRUCTION					LONGTEXT	 	NULL,
   	ANNOUNCE_OPEN_DATE			CHAR(1)			NULL
   													CHECK (ANNOUNCE_OPEN_DATE IN (0, 1)),
   	SCHEDULE_DUE_DATE			CHAR(1)			NULL
   													CHECK (SCHEDULE_DUE_DATE IN (0, 1)),
   	EMAIL_NOTIFICATION_OPTION	CHAR(1)			NULL
   													CHECK (EMAIL_NOTIFICATION_OPTION IN (0, 1, 2)),
   	RESUBMISSION_MAX_NUMBER		INTEGER			NULL,
   	RESUBMISSION_CLOSE_DATE		DATETIME		NULL,
   	ASSOCIATED_GRADEBOOK_ENTRY	VARCHAR(99)		NULL,
   	HONOR_PLEDGE				CHAR(1) 		NULL
   													CHECK (HONOR_PLEDGE IN (0, 1))
);

CREATE UNIQUE INDEX ASSIGNMENT_ASSIGNMENT_INDEX ON ASSIGNMENT_ASSIGNMENT_T
(
	ASSIGNMENT_ID
);

CREATE INDEX ASSIGNMENT_ASSIGNMENT_CONTEXT ON ASSIGNMENT_ASSIGNMENT_T
(
	CONTEXT
);

-----------------------------------------------------------------------------
-- ASSIGNMENT_ATTACHMENT_T
-----------------------------------------------------------------------------
-- The ASSIGNMENT TABLE FOR ALL ATTACHMENTS, INCLUDING ASSIGNMENT ATTACHMENTS(ATTACH_CATEGORY = 0),
-- SUBMISSION ATTACHMENTS(ATTACH_CATEGORY = 1), and  FEEDBACK ATTACHMENTS(ATTACH_CATEGORY = 2).
-----------------------------------------------------------------------------

CREATE TABLE ASSIGNMENT_ATTACHEMTN_T
(
	ATTACHMENT_ID								VARCHAR (99)	NOT NULL,
    ATTACH_TO_ID 								VARCHAR (99) 	NOT NULL,
    ATTACH_CATEGORY								CHAR(1)			NOT NULL
    												CHECK (USED_FOR IN (0, 1, 2))
);

CREATE UNIQUE INDEX ASSIGNMENT_ATTACHMENT_INDEX ON ASSIGNMENT_ATTACHMENT_T
(
	ATTACHMENT_ID
);

CREATE INDEX ASSIGNMENT_TO_ID_CONTEXT ON ASSIGNMENT_ATTACHMENT_T
(
	ATTACH_TO_ID
);
-----------------------------------------------------------------------------
-- ASSIGNMENT_SUBMISSION_T
-----------------------------------------------------------------------------

CREATE TABLE ASSIGNMENT_SUBMISSION_T
(
    SUBMISSION_ID 	VARCHAR (99) NOT NULL,
	ASSIGNMENT_ID 	VARCHAR (99) NOT NULL,
	SUBMITTER_ID 	VARCHAR(99) NOT NULL,
	RESUBMISSION_MAX_NUMBER		INTEGER		NULL,
	RESUBMISSION_CLOSE_DATE		DATETIME NULL,
	LAST_REVISION_ID	VARCHAR (99) NULL
);

CREATE UNIQUE INDEX ASSIGNMENT_SUBMISSION_INDEX ON ASSIGNMENT_SUBMISSION_T
(
	SUBMISSION_ID
);

CREATE INDEX ASSIGNMENT_SUBMISSION_CONTEXT ON ASSIGNMENT_SUBMISSION_T
(
	ASSIGNMENT_ID
);

CREATE UNIQUE INDEX ASSIGNMENT_SUBMISSION_SUBMITTER_INDEX ON ASSIGNMENT_SUBMISSION_T
(
	ASSIGNMENT_ID,SUBMITTER_ID
);
